### ISSUE TITLE
이것도 공부해보시지요 - nuxt

### ISSUE THREAD

**Issue by eggplantiny** [sh827kim/vuelog#1]
[nuxt](https://joshua1988.github.io/vue-camp/nuxt/intro.html#nuxt-%E1%84%89%E1%85%B5%E1%84%8C%E1%85%A1%E1%86%A8%E1%84%92%E1%85%A1%E1%84%80%E1%85%B5) 를 소개하는 아티클 입니다. vue 는 spa 로 작동하기 때문에 따로 Sever Side Rendering 이나 Sever Side Generator 를 설정 하지 않는다면 Search Engine Optinization 에서 불리합니다. 

그래서 SSR 과 SSG 를 쉽게 할 수 있도록 도와주는 Vue Framework 인 Nuxt 를 많이 사용합니다.

해당 레포를 직접 블로그로 쓰실지 아니면 공부용도로 쓰시는진 잘 모르겠지만 진짜 블로그로 쓰실거면 nuxt 로 개발하시는걸 적극 추천 드립니다.

**Comment by sh827kim** [comment]
우선은 천천히 공부하는 용도로 만들어보는 자잘한 토이 프로젝트에요. 말씀하시는 nuxt 관련해서는 vue 기본 내용을 어느정도 습득하고 다음 공부 타겟으로 잡아보겠습니다 😃 다음 커리큘럼 추천 감사합니다~
